config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :photos do
    resources :comments, only: [:create]
  end
  
  devise_for :users, controllers: {
  registrations: 'users/registrations',
  sessions: 'users/sessions',
  passwords: 'users/passwords'
}

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "photos#index"
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_one_attached :image

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /photos or /photos.json
  def index
    @photos = Photo.all
  end
  
  

  # GET /photos/1 or /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos or /photos.json
  def create
    @photo = Photo.new(photo_params)

    if @photo.save
      redirect_to @photo, notice: "Photo created successfully"
    else
      render :new
    end
  end

  # PATCH/PUT /photos/1 or /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to photo_url(@photo), notice: "Photo was successfully updated." }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1 or /photos/1.json
  def destroy
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url, notice: "Photo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def photo_params
      params.require(:photo).permit(:caption, :user_id, :image)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_with(model: photo, class: "needs-validation", novalidate: true) do |form| %>
  <% if photo.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
        <% photo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :caption, class: "form-label" %>
    <%= form.text_field :caption, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :user_id, class: "form-label" %>
    <%= form.text_field :user_id, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="mb-3">
    <%= form.submit "Create", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/photos/_photo.html.erb
<div id="<%= dom_id photo %>">
  <p>
    <strong>Caption:</strong>
    <%= photo.caption %>
  </p>

  <p>
    <strong>User:</strong>
    <%= photo.user_id %>
  </p>

</div>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render "form", photo: @photo %>

<br>

<div>
  <%= link_to "Show this photo", @photo %> |
  <%= link_to "Back to photos", photos_path %>
</div>

app/views/photos/index.html.erb
<div id="photos">
  <div class="container">
    <div class="row">
      <% @photos.each_slice(3) do |group| %>
        <div class="row justify-content-center">
          <% group.each do |photo| %>
            <div class="col-md-4">
              <div class="card mb-4">
                <%= image_tag photo.image, class: "card-img-top", alt: "Photo" %>
                <div class="card-body text-center">
                  <h5 class="card-title"><%= photo.caption %></h5>
                  <p class="card-text">Comments:</p>
                  <% photo.comments.each do |comment| %>
                    <div class="comment">
                      <% if comment.user.profile_picture.attached? %>
                        <%= image_tag comment.user.profile_picture, class: "rounded-circle", style: "width: 50px; height: 50px;" %>
                      <% else %>
                        <%= image_tag "default_profile_picture.png", class: "rounded-circle", style: "width: 50px; height: 50px;" %>
                      <% end %>
                      <p><strong><%= comment.user.email %>:</strong> <%= comment.content %></p>
                    </div>
                  <% end %>
                  <%= form_with(model: Comment.new, url: photo_comments_path(photo), class: "mt-3") do |form| %>
                    <%= form.hidden_field :photo_id, value: photo.id %>
                    <div class="form-group">
                      <%= form.label :content %>
                      <%= form.text_area :content, rows: 3, class: "form-control" %>
                    </div>
                    <%= form.submit "Comentar", class: "btn btn-primary mt-3" %>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render "form", photo: @photo %>

<br>

<div>
  <%= link_to "Back to photos", photos_path %>
</div>

app/views/photos/show.html.erb
# app/views/photos/show.html.erb
<% @photo.comments.each do |comment| %>
  <div class="comment">
    <%= image_tag url_for(comment.user.profile_picture), class: 'profile-picture' if comment.user.profile_picture.attached? %>
    <p><%= comment.content %></p>
  </div>
<% end %>